apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 613795541064-3tfrp352a64o07h02la1s4k71ccaa9pf.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://89.116.22.115.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
