apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLV9NWjdLZnByeW1tU1pCOXJYalRQZXloV0pYcXU=
  NEXTAUTH_SECRET: jfxuwmSXn6XmUkGH2lS9MHrQ+rnQWo08DfhfGL8e7bw=
  NEXT_PUBLIC_API_KEY: QUl6YVN5QzV4d2NtdjRHSTJoRDRQRTBiUGdaSVBTbnBKYVlwY0dn
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==
