apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: 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
  NEXTAUTH_SECRET: jfxuwmSXn6XmUkGH2lS9MHrQ+rnQWo08DfhfGL8e7bw=
  NEXT_PUBLIC_API_KEY: AIzaSyC5xwcmv4GI2hD4PE0bPgZIPSnpJaYpcGg
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==
