apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLTJyVjRHQjQ5ckpPQlNXMkJSTjE2NXA3bkxIZC0=
  NEXTAUTH_SECRET: QkxVdmtHVU96blV2UzVxemlyck1hN1VhbGduNDcrQlBOSWVMQXNZYUJmYz0=
  NEXT_PUBLIC_API_KEY: AIzaSyBa0Yif4RJePCEhLbI4yUNbtPJz5BzarqE
  MONGO_INITDB_ROOT_PASSWORD: UjRYQlF2ckN6YkRMQ3lEYg==